import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { CartProvider } from "@/contexts/cart-context";

const B = localFont({
  src: "./fonts/bbtorsospro-bold.otf"

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${B.className} min-h-svh overflow-x-hidden antialiased text-pretty`}
      >
        <div vaul-drawer-wrapper="">
          <div className="relative flex min-h-svh flex-col">
            <CartProvider>{children}</CartProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
